### ISSUE TITLE
[BUG] last_reset move into set_state, too

### ISSUE THREAD

**Issue by unl0ck** [unixorn/ha-mqtt-discoverable#288]
**Describe the bug**
I missed to expand the set_state in sensor for set last_reset if set Total

SOrry for this

**Comment by unl0ck** [comment]
@unixorn i have to set the last_reset in set_state or ? 
how will it send via mqtt ? maybe i missed more to add

https://developers.home-assistant.io/docs/core/entity/sensor/#state-class-sensorstateclasstotal

**Comment by unl0ck** [comment]
@unixorn  sorry bro I made a mistake, how can I test it in front of ? 

` File "/usr/local/lib/python3.12/site-packages/ha_mqtt_discoverable/sensors.py", line 337, in set_state
    self._state_helper(str(state), last_reset=last_reset)
  File "/usr/local/lib/python3.12/site-packages/ha_mqtt_discoverable/__init__.py", line 749, in _state_helper
    message_info = self.mqtt_client.publish(topic, state, retain=retain)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/paho/mqtt/client.py", line 1247, in publish
    raise TypeError(
TypeError: payload must be a string, bytearray, int, float or None.
Exception in thread Thread-62 (historical_data_task):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/build/GridboxConnector/__main__.py", line 59, in historical_data_task
    ha_viessmann_historical_device.update_sensors(total, midnight_today.isoformat())
  File "/build/GridboxConnector/ha_viessmann_gridbox_connector.py", line 106, in update_sensors
    self.production_sensor.set_state(measurement.get("production", ""), last_reset=last_reset)
  File "/usr/local/lib/python3.12/site-packages/ha_mqtt_discoverable/sensors.py", line 337, in set_state
    self._state_helper(str(state), last_reset=last_reset)
  File "/usr/local/lib/python3.12/site-packages/ha_mqtt_discoverable/__init__.py", line 749, in _state_helper
    message_info = self.mqtt_client.publish(topic, state, retain=retain)`

**Comment by unl0ck** [comment]
I will push after Christmas an bug fix :( I am so sorry.

**Comment by unl0ck** [comment]
#294 @unixorn pushed fix with added unit test now it should working

**Comment by unixorn** [comment]
Thanks for your help improving the project.
